
image: golang:latest

stages:
  - test
  - build


format:
  stage: test
  script:
    - DISPLAY=:0 export PATH=$PATH:/usr/local/go/bin
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

compile:
  stage: build
  script:
    - DISPLAY=:0 export PATH=$PATH:/usr/local/go/bin
    - mkdir -p zru
    - go build -o zru ./...
  artifacts:
    paths:
      - zru


